#!/usr/bin/env python3

import sys
from helpers import * 
from analyzer import Analyzer
from termcolor import colored

def main():

	# ensure proper usage
	if len(sys.argv) != 2:
		sys.exit( "Usage: ./tweets @screen_name" )
	
	tweets = get_user_timeline( sys.argv[1], count=50 )
	
	# absolute paths to lists
	positives = os.path.join(sys.path[0], "positive-words.txt")
	negatives = os.path.join(sys.path[0], "negative-words.txt")

	# instantiate analyzer
	analyzer = Analyzer(positives, negatives)

	# analyze word
	for tweet in tweets:
		score = analyzer.analyze( tweet )
		tweet_formated = "{} {}".format(score, tweet);
		if score > 0.0:
			print(colored(tweet_formated , "green"))
		elif score < 0.0:
			print(colored(tweet_formated, "red"))
		else:
			print(colored(tweet_formated, "yellow"))


if __name__ == '__main__':
	main();